In [1]:
import numpy as np
import pandas as pd
from numpy.random import randn

In [2]:
my_series = [1,23,4,5]
my_index = ['A','B','C','D']
my_comb = pd.Series(my_series,my_index)
my_comb

A     1
B    23
C     4
D     5
dtype: int64

In [3]:
cars = {"Tesla":9,"Audi":7,"Lambo":10}
my_car = pd.Series(cars)
my_car

Tesla     9
Audi      7
Lambo    10
dtype: int64

In [4]:
my_data = randn(4,3)
my_row = ['A','B','C','D']
my_col = ['Sun','Mon','Tue']

In [5]:
my_df = pd.DataFrame(my_data,my_row,my_col)
my_df

        Sun       Mon       Tue
A -0.009880  0.227692 -0.016875
B  0.113255  1.197618 -1.418260
C -0.362619  1.095996 -0.311327
D -0.785388  1.441822  1.528809

## Cleaing,and analysing Dataset

In [6]:
df = pd.read_csv("netflix1.csv",delimiter=",")
df.loc[[0,5,100]]
df.head(5)
df.tail(5)
# df.info()
df.shape
df.ndim
df.dtypes
df.columns
df.describe()
df['country'].describe()

count              8790
unique               86
top       United States
freq               3240
Name: country, dtype: object

In [7]:
df['country'].value_counts(ascending=True)
df['title'].value_counts(ascending=True,dropna=False)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   object
 1   type          8790 non-null   object
 2   title         8790 non-null   object
 3   director      8790 non-null   object
 4   country       8790 non-null   object
 5   date_added    8789 non-null   object
 6   release_year  8789 non-null   float64
 7   rating        8790 non-null   object
 8   duration      8788 non-null   object
 9   listed_in     8790 non-null   object
dtypes: float64(1), object(9)
memory usage: 686.8+ KB

In [8]:
df.iloc[0:5]
df['release_year']=df['release_year'].astype(dtype='float16')
df['release_year'].dtype

dtype('float16')

In [9]:
arr = my_df.to_numpy(dtype="float16").tolist()
arr

[[-0.00988006591796875, 0.2276611328125, -0.016876220703125],
 [0.11328125, 1.197265625, -1.41796875],
 [-0.362548828125, 1.095703125, -0.311279296875],
 [-0.78515625, 1.44140625, 1.529296875]]

In [10]:
date = pd.to_datetime(df['date_added'],format='%m/%d/%Y')
date = pd.to_datetime(date , errors='coerce') # first this 
date = date.dt.strftime('%m-%d-%Y') # then this to change the format

date.head(6)

0    09-25-2021
1    09-24-2021
2    09-24-2021
3    09-22-2021
4    09-24-2021
5    09-24-2021
Name: date_added, dtype: object

In [11]:
df.isna().sum()
df.isna().any()
s_200=df[df['release_year']==2000]
s_200.describe()

/home/samrat01/.local/lib/python3.10/site-packages/numpy/core/_methods.py:49: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)

       release_year
count          37.0
mean            inf
std             0.0
min          2000.0
25%          2000.0
50%          2000.0
75%          2000.0
max          2000.0